//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAppTelegramBot13950202.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("86")]
        public string settingLastid {
            get {
                return ((string)(this["settingLastid"]));
            }
            set {
                this["settingLastid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("287401999:AAG_D0e0k1MHTAt8JhK9UPYPfZkGTKBzyeE")]
        public string settingToken {
            get {
                return ((string)(this["settingToken"]));
            }
            set {
                this["settingToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srv-shptest")]
        public string settingShpSrv {
            get {
                return ((string)(this["settingShpSrv"]));
            }
            set {
                this["settingShpSrv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ticketing")]
        public string settingTargetList {
            get {
                return ((string)(this["settingTargetList"]));
            }
            set {
                this["settingTargetList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string settingInterval {
            get {
                return ((string)(this["settingInterval"]));
            }
            set {
                this["settingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contacts")]
        public string settingListContact {
            get {
                return ((string)(this["settingListContact"]));
            }
            set {
                this["settingListContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151370482")]
        public string settingTelegramAdminId {
            get {
                return ((string)(this["settingTelegramAdminId"]));
            }
            set {
                this["settingTelegramAdminId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\logs\\")]
        public string settingLogLoc {
            get {
                return ((string)(this["settingLogLoc"]));
            }
            set {
                this["settingLogLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("welcome please give me username and password")]
        public string settingWelcomMsg {
            get {
                return ((string)(this["settingWelcomMsg"]));
            }
            set {
                this["settingWelcomMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("telegram")]
        public string settingTelegramField {
            get {
                return ((string)(this["settingTelegramField"]));
            }
            set {
                this["settingTelegramField"] = value;
            }
        }
    }
}
